In [ ]:
!pip install --q "snowflake-connector-python[pandas]"
!sudo pip install --q  snowflake-ml-python==1.0.11 -U
!pip install --upgrade --q snowflake-snowpark-python==1.9.0
!pip install --q seaborn
!pip install --upgrade --q xgboost==1.7.3
!pip install --upgrade --q numpy==1.24.3
!pip install --upgrade --q pandas==1.5.3
!pip install --upgrade --q anyio==3.5.0
!pip install --upgrade --q packaging==23.1
!pip install --upgrade --q scikit-learn==1.3.0
!pip install --upgrade --q typing-extensions==4.7.1
!pip install --upgrade --q cryptography==39.0.0
!pip install --upgrade --q fsspec==2023.9.2
!pip install --q xgboost
!pip install --q catboost
!pip install --q refractml

^C
ERROR: Operation cancelled by user
You should consider upgrading via the 'pip install --upgrade pip' command.


In [4]:
from snowflake.snowpark import Session

# Data Science Libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# create_temp_table warning suppresion
import warnings; warnings.simplefilter('ignore')
import configparser

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier


from xgboost import XGBClassifier
from catboost import CatBoostClassifier

Matplotlib created a temporary cache directory at /tmp/matplotlib-ej_1pi4c because the default path (/home/mosaic-ai/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [5]:
config = configparser.ConfigParser()
config.read("snowflake_connection.ini")

['snowflake_connection.ini']

In [6]:
connection_parameters = {
    "user": f'{config["Snowflake"]["user"]}',
    "password": f'{config["Snowflake"]["password"]}',
    #"password": os.getenv('snowflake_password'),
    "account": f'{config["Snowflake"]["account"]}',
    #"account": os.getenv('snowflake_account'),
    "WAREHOUSE": f'{config["Snowflake"]["WAREHOUSE"]}',
    "DATABASE": f'{config["Snowflake"]["DATABASE"]}',
    "SCHEMA": f'{config["Snowflake"]["SCHEMA"]}'
}

In [7]:
def snowflake_connector(conn):
    try:
        session = Session.builder.configs(conn).create()
        print("connection successful!")
    except:
        raise ValueError("error while connecting with db")
    return session

session = snowflake_connector(connection_parameters)

connection successful!


In [8]:
df = session.table("AUTO_INSURANCE_CLAIMS_DATA_PRODUCT")
insurance_claim = df.to_pandas()

In [9]:
insurance_claim.columns = insurance_claim.columns.str.lower()

In [10]:
insurance_claim.columns

Index(['months_as_customer', 'customer_age', 'policy_number',
       'policy_bind_date', 'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital_gains', 'capital_loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day', 'incident_time_of_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount_paid',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='object')

In [11]:
insurance_claim.rename(columns = {'total_claim_amount_paid': 'total_claim_amount'}, inplace=True)

In [12]:
insurance_claim=insurance_claim.replace("?",np.NaN)

In [13]:
df = insurance_claim.copy()

In [14]:
# dropping columns which are not necessary for prediction

to_drop = ['policy_number','policy_bind_date','policy_state','insured_zip','incident_location','incident_date',
           'incident_state','incident_city','insured_hobbies','auto_make','auto_model','auto_year']

df.drop(to_drop, inplace=True, axis=1)

In [15]:
# separating the feature and target columns

X = df.drop('fraud_reported', axis = 1)
y = df['fraud_reported']

In [16]:
# extracting categorical columns
cat_df = X.select_dtypes(include = ['object'])

In [17]:
cat_df.columns

Index(['customer_age', 'policy_csl', 'insured_sex', 'insured_education_level',
       'insured_occupation', 'insured_relationship', 'incident_type',
       'collision_type', 'incident_severity', 'authorities_contacted',
       'incident_time_of_day', 'property_damage', 'police_report_available'],
      dtype='object')

In [18]:
# printing unique values of each column
for col in cat_df.columns:
    print(f"{col}: \n{cat_df[col].unique()}\n")

customer_age: 
['58' '31' '54' '61' '41' '32' '48' '24' '66' '57' '62' '56' '68' '26'
 '28' '64' '43' '46' '42' '21' '49' '59' '52' '47' '22' '63' '65' '69'
 '35' '37' '60' '30' '40' '20' '39' '45' '19' '67' '33' '29' '44' '34'
 '23' '53' '38' '27' '50' '55' '36' '25' '51']

policy_csl: 
['250/500' '100/300' '500/1000']

insured_sex: 
['FEMALE' 'MALE']

insured_education_level: 
['MD' 'College' 'Masters' 'Associate' 'High School' 'PhD' 'JD']

insured_occupation: 
['tech-support' 'adm-clerical' 'sales' 'machine-op-inspct'
 'prof-specialty' 'farming-fishing' 'exec-managerial' 'priv-house-serv'
 'handlers-cleaners' 'other-service' 'armed-forces' 'craft-repair'
 'transport-moving' 'protective-serv']

insured_relationship: 
['other-relative' 'husband' 'wife' 'own-child' 'not-in-family' 'unmarried']

incident_type: 
['Multi-vehicle Collision' 'Single Vehicle Collision' 'Parked Car'
 'Vehicle Theft']

collision_type: 
['Details not Available' 'Front Collision' 'Rear Collision'
 'Side Collisio

In [19]:
cat_df = pd.get_dummies(cat_df, drop_first = True)

In [20]:
num_df = df.select_dtypes(include = ['int16','int8','int32','float64'])

In [21]:
num_df.columns

Index(['months_as_customer', 'policy_deductable', 'policy_annual_premium',
       'umbrella_limit', 'capital_gains', 'capital_loss',
       'incident_hour_of_the_day', 'number_of_vehicles_involved',
       'bodily_injuries', 'witnesses', 'total_claim_amount', 'injury_claim',
       'property_claim', 'vehicle_claim'],
      dtype='object')

In [22]:
# combining the Numerical and Categorical dataframes to get the final dataset

X = pd.concat([num_df, cat_df], axis = 1)

In [23]:
# splitting data into training set and test set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [24]:
num_df = X_train[['months_as_customer', 'policy_deductable', 'umbrella_limit',
       'capital_gains', 'capital_loss', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'injury_claim', 'property_claim',
       'vehicle_claim']]

In [25]:
num_df_test = X_test[['months_as_customer', 'policy_deductable', 'umbrella_limit',
       'capital_gains', 'capital_loss', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'bodily_injuries', 'witnesses', 'injury_claim', 'property_claim',
       'vehicle_claim']]

In [26]:
# Scaling the numeric values in the dataset

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(num_df)

In [27]:
scaled_data_test = scaler.transform(num_df_test)

In [28]:
scaled_num_df = pd.DataFrame(data = scaled_data, columns = num_df.columns, index = X_train.index)
scaled_num_df.head()

months_as_customer  policy_deductable  umbrella_limit  capital_gains   
78260            -0.922218          -1.286837        1.014694      -0.712308  \
193891            1.980096           0.252036        1.369086       1.131135   
114736           -0.911224          -1.260659        0.710815      -0.872429   
225365           -0.779301          -0.217292       -0.395344       0.072997   
122050            0.056214           0.758761        0.632595      -0.155629   

        capital_loss  incident_hour_of_the_day  number_of_vehicles_involved   
78260      -0.455184                 -0.008822                    -0.678643  \
193891      0.123003                  0.503033                     0.747867   
114736     -0.554963                  1.014889                     2.174376   
225365     -0.797714                 -0.008822                    -0.678643   
122050      0.827875                  0.332415                    -0.678643   

        bodily_injuries  witnesses  injury_claim  property_claim   
78260          1.227446   1.343199      0.050396        1.700563  \
193891         0.004975   1.343199      0.066058        0.403058   
114736         0.004975   0.446423      1.957127       -0.984640   
225365        -1.217496  -0.450353     -1.009878       -0.940178   
122050         1.227446   1.343199      1.981180       -0.948562   

        vehicle_claim  
78260        0.835867  
193891      -0.466528  
114736       1.321046  
225365       0.112690  
122050      -0.543544

In [29]:
scaled_num_df_test = pd.DataFrame(data = scaled_data_test, columns = num_df_test.columns, index = X_test.index)
scaled_num_df_test.head()

months_as_customer  policy_deductable  umbrella_limit  capital_gains   
125868            1.067626           1.200041       -0.113806       1.578596  \
121180            1.782211           0.482025       -0.386623       0.445437   
54606            -0.856256           0.798027       -0.623614      -0.966745   
120570           -0.834269           1.839524       -0.994375      -0.414241   
50824             1.034646           1.987241        1.391252      -1.715945   

        capital_loss  incident_hour_of_the_day  number_of_vehicles_involved   
125868      0.193146                  1.185507                    -0.678643  \
121180      1.383184                 -0.179441                     0.747867   
54606       1.199452                 -0.691297                     2.174376   
120570      0.205781                  1.356126                    -0.678643   
50824      -0.333242                  1.014889                     2.174376   

        bodily_injuries  witnesses  injury_claim  property_claim   
125868         0.004975  -1.347129      1.486423       -0.970920  \
121180         0.004975  -1.347129      1.209258       -0.977526   
54606         -1.217496  -1.347129     -1.023862       -0.958725   
120570         1.227446  -0.450353     -0.865702       -0.979812   
50824          0.004975   0.446423      0.601649       -0.946149   

        vehicle_claim  
125868      -1.329138  
121180      -1.454928  
54606        1.539727  
120570      -1.289546  
50824       -0.806153

In [30]:
X_train.drop(columns = scaled_num_df.columns, inplace = True)

In [31]:
X_train = pd.concat([scaled_num_df, X_train], axis = 1)

In [32]:
X_test.drop(columns = scaled_num_df_test.columns, inplace = True)

In [33]:
X_test = pd.concat([scaled_num_df_test, X_test], axis = 1)

# Stochastic Gradient Boosting

In [55]:
sgb = GradientBoostingClassifier(subsample = 0.90, max_features = 0.70)
sgb.fit(X_train, y_train)

GradientBoostingClassifier(max_features=0.7, subsample=0.9)

In [51]:
y_pred = sgb.predict(X_test)

In [52]:
y_prob = sgb.predict_proba(X_test)[:,1]

In [53]:
sgb_train_acc = accuracy_score(y_train, sgb.predict(X_train))
sgb_test_acc = accuracy_score(y_test, y_pred)

print(f"Training accuracy of CatBoost is : {sgb_train_acc}")
print(f"Test accuracy of CatBoost is : {sgb_test_acc}")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Training accuracy of CatBoost is : 0.8528554679051554
Test accuracy of CatBoost is : 0.8529376611402325
[[   14  8613]
 [    0 49940]]
                   precision    recall  f1-score   support

   Fraud Reported       1.00      0.00      0.00      8627
No Fraud Reported       0.85      1.00      0.92     49940

         accuracy                           0.85     58567
        macro avg       0.93      0.50      0.46     58567
     weighted avg       0.87      0.85      0.79     58567



# CATBoost

In [56]:
cat = CatBoostClassifier(iterations=10)
cat.fit(X_train, y_train)

Learning rate set to 0.5
0:	learn: 0.4773611	total: 90.8ms	remaining: 817ms
1:	learn: 0.4262490	total: 179ms	remaining: 717ms
2:	learn: 0.4163634	total: 264ms	remaining: 616ms
3:	learn: 0.4134074	total: 292ms	remaining: 438ms
4:	learn: 0.4113457	total: 368ms	remaining: 368ms
5:	learn: 0.4106672	total: 394ms	remaining: 263ms
6:	learn: 0.4093667	total: 473ms	remaining: 203ms
7:	learn: 0.4086592	total: 555ms	remaining: 139ms
8:	learn: 0.4080474	total: 586ms	remaining: 65.2ms
9:	learn: 0.4075486	total: 670ms	remaining: 0us


In [57]:
cat_acc = accuracy_score(y_test, cat.predict(X_test))

In [58]:
print(f"Training Accuracy of Cat Boost Classifier is {accuracy_score(y_train, cat.predict(X_train))}")
print(f"Test Accuracy of Cat Boost Classifier is {cat_acc} \n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, cat.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, cat.predict(X_test))}")

Training Accuracy of Cat Boost Classifier is 0.8525424307618755
Test Accuracy of Cat Boost Classifier is 0.8528522888315946 

Confusion Matrix :- 
[[    9  8618]
 [    0 49940]]

Classification Report :- 
                    precision    recall  f1-score   support

   Fraud Reported       1.00      0.00      0.00      8627
No Fraud Reported       0.85      1.00      0.92     49940

         accuracy                           0.85     58567
        macro avg       0.93      0.50      0.46     58567
     weighted avg       0.87      0.85      0.79     58567



# Gradient Boosting

In [59]:
gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [60]:
gb_acc = accuracy_score(y_test, gb.predict(X_test))

In [61]:
print(f"Training Accuracy of Gradient Boosting Classifier is {accuracy_score(y_train, gb.predict(X_train))}")
print(f"Test Accuracy of Gradient Boosting Classifier is {gb_acc} \n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, gb.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, gb.predict(X_test))}")

Training Accuracy of Gradient Boosting Classifier is 0.8523261505537911
Test Accuracy of Gradient Boosting Classifier is 0.8527669165229567 

Confusion Matrix :- 
[[    4  8623]
 [    0 49940]]

Classification Report :- 
                    precision    recall  f1-score   support

   Fraud Reported       1.00      0.00      0.00      8627
No Fraud Reported       0.85      1.00      0.92     49940

         accuracy                           0.85     58567
        macro avg       0.93      0.50      0.46     58567
     weighted avg       0.87      0.85      0.79     58567



# Adaboost

In [64]:
ada = AdaBoostClassifier(n_estimators=100, random_state=0)
ada.fit(X_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=0)

In [65]:
ada_acc = accuracy_score(y_test, ada.predict(X_test))

In [67]:
print(f"Training Accuracy of Adaboosting Classifier is {accuracy_score(y_train, ada.predict(X_train))}")
print(f"Test Accuracy of Adaboosting Classifier is {ada_acc} \n")

print(f"Confusion Matrix :- \n{confusion_matrix(y_test, ada.predict(X_test))}\n")
print(f"Classification Report :- \n {classification_report(y_test, ada.predict(X_test))}")

Training Accuracy of Adaboosting Classifier is 0.8522066272809025
Test Accuracy of Adaboosting Classifier is 0.852664469752591 

Confusion Matrix :- 
[[    4  8623]
 [    6 49934]]

Classification Report :- 
                    precision    recall  f1-score   support

   Fraud Reported       0.40      0.00      0.00      8627
No Fraud Reported       0.85      1.00      0.92     49940

         accuracy                           0.85     58567
        macro avg       0.63      0.50      0.46     58567
     weighted avg       0.79      0.85      0.79     58567



# Voting Classifier

In [68]:
classifiers = [('Ada Boost', ada),('Gradient Boosting Classifier', gb), ('SGB', sgb),('Cat Boost', cat)]

In [69]:
vc = VotingClassifier(estimators = classifiers)
vc.fit(X_train, y_train)

Learning rate set to 0.5
0:	learn: 0.4773611	total: 83.8ms	remaining: 754ms
1:	learn: 0.4262490	total: 123ms	remaining: 492ms
2:	learn: 0.4163634	total: 228ms	remaining: 533ms
3:	learn: 0.4134074	total: 315ms	remaining: 472ms
4:	learn: 0.4113457	total: 403ms	remaining: 403ms
5:	learn: 0.4106672	total: 488ms	remaining: 326ms
6:	learn: 0.4093667	total: 521ms	remaining: 223ms
7:	learn: 0.4086592	total: 605ms	remaining: 151ms
8:	learn: 0.4080474	total: 691ms	remaining: 76.8ms
9:	learn: 0.4075486	total: 721ms	remaining: 0us


VotingClassifier(estimators=[('Ada Boost',
                              AdaBoostClassifier(n_estimators=100,
                                                 random_state=0)),
                             ('Gradient Boosting Classifier',
                              GradientBoostingClassifier()),
                             ('SGB',
                              GradientBoostingClassifier(max_features=0.7,
                                                         subsample=0.9)),
                             ('Cat Boost',
                              <catboost.core.CatBoostClassifier object at 0x7fc6cac73220>)])

In [70]:
y_pred = vc.predict(X_test)

In [71]:
vc_train_acc = accuracy_score(y_train, vc.predict(X_train))
vc_test_acc = accuracy_score(y_test, y_pred)

print(f"Training accuracy of Voting Classifier is : {vc_train_acc}")
print(f"Test accuracy of Voting Classifier is : {vc_test_acc}")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Training accuracy of Voting Classifier is : 0.8522578515407119
Test accuracy of Voting Classifier is : 0.8527669165229567
[[    4  8623]
 [    0 49940]]
                   precision    recall  f1-score   support

   Fraud Reported       1.00      0.00      0.00      8627
No Fraud Reported       0.85      1.00      0.92     49940

         accuracy                           0.85     58567
        macro avg       0.93      0.50      0.46     58567
     weighted avg       0.87      0.85      0.79     58567

